backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/images" # Media files will be stored in the repo under assets/images
public_folder: "assets/images" # The src attribute for uploaded media will begin with /assets/images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero Heading", name: "hero_heading", widget: "string"}
          - {label: "Hero Subheading", name: "hero_subheading", widget: "string"}
  - name: "testimonials"
    label: "Testimonials"
    files:
      - file: "data/testimonials.json"
        label: "Testimonials List"
        name: "testimonials_list"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "string"}
              - {label: "Author", name: "author", widget: "string"}
  - name: "blog"
    label: "Blog Posts"
    files:
      - file: "data/posts.json"
        label: "Blog Posts List"
        name: "posts_list"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime"}
              - {label: "Author", name: "author", widget: "string", default: "John Paine"}
              - {label: "Featured Image", name: "image", widget: "image", required: false}
              - {label: "Summary", name: "summary", widget: "text", required: false}
              - {label: "Body", name: "body", widget: "markdown"}
